global using EMS.Core.Services.ApplicationUser.Implementation;
global using EMS.Core.Services.Identity.Interface;
global using EMS.Core.Services.Wallets.Interface;
global using EMS.Data.Entities;
global using Microsoft.AspNetCore.Identity;
global using Moq;
global using System.Threading.Tasks;
global using TanvirArjel.EFCore.GenericRepository;
global using Xunit;