global using Microsoft.AspNetCore.Identity;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using EMS.Data.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Http;
global using EMS.Data.Persistence;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;